package com.dooapp.firea.entity;

import org.jdom2.Attribute;
import org.jdom2.Element;

//Start of user code for imports
// TODO: import me!
//End of user code


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.dooapp.firea.wrapper.Project;
import com.dooapp.lib.common.entity.Bean;


/*
 * Class
 * <!-- Start of user code comment for Project Class
 * End of user code -->
 */
//Start of user code for queries
//End of user code

@javax.persistence.Entity
public class ProjectBean
//Start of user code bloc for inheritance

//End of user code
//Start of user code bloc for interfaces
 implements Bean
//End of user code
{
	//Start of user code for attributes
	// Other attributes
	//End of user code

	/**
	 * The logger
	 */
	private static final Logger logger = LoggerFactory.getLogger(ProjectBean.class);

	
	private String Status;
	
	@javax.persistence.ManyToOne(cascade = javax.persistence.CascadeType.ALL)
	private ContactBean contacts;
	@javax.persistence.Column(name = "CREATION_DATE")
	@javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date creationDate;
	
	private String description;
	
	@javax.persistence.OneToOne(optional = false, cascade = javax.persistence.CascadeType.ALL)
	private GazConfigurationBean gazconfiguration;
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "seq", initialValue = 1, allocationSize = 10)
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.SEQUENCE, generator = "seq")
	@javax.persistence.Column(name = "ID")
	private long id;
	
	@javax.persistence.ManyToOne(cascade = javax.persistence.CascadeType.ALL)
	private PersistentImageBean image;
	
	private String kind;
	
	@javax.persistence.Column(name = "NAMECOLUMN")
	private String name;
	
	@javax.persistence.ManyToOne(cascade = javax.persistence.CascadeType.ALL)
	private RisqueBean risque;
	
	@javax.persistence.OneToOne(optional = false, cascade = javax.persistence.CascadeType.ALL, mappedBy = "project")
	private SampleBean sample;
	@javax.persistence.Column(name = "UPDATE_DATE")
	@javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date updateDate;
	@javax.persistence.Version
	@javax.persistence.Column(name = "VERSIONCOLUMN")
	private int version;

	@javax.persistence.Transient
	private Project wrapper;
    	
	/**
	 * The current UUID of this object.<br>
	 * It's generated by the JPA provider, so you do not have to do it yourself.<br>
	 * <br>
	 * 
	 * @see <a
	 *      href="http://openjpa.apache.org/builds/2.1.1/apache-openjpa-2.1.1/docs/jpa_overview_meta_field.html#jpa_overview_meta_gen">jpa
	 *      documentation</a>
	 * @see <a href="http://fr.wikipedia.org/wiki/UUID">wikipedia</a>
	 */
	@javax.persistence.Column(name = "UUID", columnDefinition = "CHAR(36)")
	protected String uuid;
	/*
	 * <!-- Start of user code comment for Project wrapper getter
	 * End of user code -->
	 */
	@javax.persistence.Transient
	@Override
	public Project getWrapper() {
		if (wrapper == null) {
			wrapper = new Project(this);
		}
		return wrapper;
	}
	
	@javax.persistence.Transient
	@Override
	public boolean isWrapped() { 
		return wrapper != null;
	}
	
	/*
	 * <!-- Start of user code comment for Project wrapper setter
	 * End of user code -->
	 */
	@javax.persistence.Transient
	public void setWrapper(Project wrapper) {
		if (this.wrapper != null && this.wrapper != wrapper) {
			throw new RuntimeException("A bean can only have one wrapper, use #getWrapper instead");
		}
		this.wrapper = wrapper;
	}

	/**
	 * Configure date and identifiant when persisting the object the first time
	 */
	@javax.persistence.PrePersist
	void initDates() {
		updateDate = new java.util.Date();
		creationDate = new java.util.Date();
		if (uuid == null) {
			uuid = java.util.UUID.randomUUID().toString();
		}
	}
	
	/**
	 * Configure the update date when updating the object
	 */
	@javax.persistence.PreUpdate
	void initUpdateDate() {
		updateDate = new java.util.Date();
	}
	

	/*
	 * <!-- Start of user code comment for Status getter
	 * End of user code -->
	 */
	public String getStatus(){
		return this.Status;
	}
	
	/*
	 * <!-- Start of user code comment for Status setter
	 * End of user code -->
	 */
	public void setStatus(String arg0){
		this.Status = arg0;
	}
	/*
	 * <!-- Start of user code comment for contacts getter
	 * End of user code -->
	 */
	public ContactBean getContacts(){
		return this.contacts;
	}
	
	/*
	 * <!-- Start of user code comment for contacts setter
	 * End of user code -->
	 */
	public void setContacts(ContactBean arg0){
		this.contacts = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for contacts unsetter
	 * End of user code -->
	 */
	public void unsetContacts(){
			this.contacts = null;
			
	} 
	/*
	 * <!-- Start of user code comment for creationDate getter
	 * End of user code -->
	 */
	public java.util.Date getCreationDate(){
		return this.creationDate;
	}
	
	/*
	 * <!-- Start of user code comment for creationDate setter
	 * End of user code -->
	 */
	public void setCreationDate(java.util.Date arg0){
		this.creationDate = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for creationDate unsetter
	 * End of user code -->
	 */
	public void unsetCreationDate(java.util.Date arg0){
		this.creationDate = null;
	}
	/*
	 * <!-- Start of user code comment for description getter
	 * End of user code -->
	 */
	public String getDescription(){
		return this.description;
	}
	
	/*
	 * <!-- Start of user code comment for description setter
	 * End of user code -->
	 */
	public void setDescription(String arg0){
		this.description = arg0;
	}
	/*
	 * <!-- Start of user code comment for gazconfiguration getter
	 * End of user code -->
	 */
	public GazConfigurationBean getGazconfiguration(){
		return this.gazconfiguration;
	}
	
	/*
	 * <!-- Start of user code comment for gazconfiguration setter
	 * End of user code -->
	 */
	public void setGazconfiguration(GazConfigurationBean arg0){
		this.gazconfiguration = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for gazconfiguration unsetter
	 * End of user code -->
	 */
	public void unsetGazconfiguration(){
			if (this.gazconfiguration == null) {
				return;
			}
			GazConfigurationBean oldgazconfiguration = this.gazconfiguration;
			this.gazconfiguration = null;
			oldgazconfiguration.unsetProject();
	} 
	/*
	 * <!-- Start of user code comment for id getter
	 * End of user code -->
	 */
	public long getId(){
		return this.id;
	}
	
	/*
	 * <!-- Start of user code comment for id setter
	 * End of user code -->
	 */
	public void setId(long arg0){
		this.id = arg0;
	}
	/*
	 * <!-- Start of user code comment for image getter
	 * End of user code -->
	 */
	public PersistentImageBean getImage(){
		return this.image;
	}
	
	/*
	 * <!-- Start of user code comment for image setter
	 * End of user code -->
	 */
	public void setImage(PersistentImageBean arg0){
		this.image = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for image unsetter
	 * End of user code -->
	 */
	public void unsetImage(){
			this.image = null;
			
	} 
	/*
	 * <!-- Start of user code comment for kind getter
	 * End of user code -->
	 */
	public String getKind(){
		return this.kind;
	}
	
	/*
	 * <!-- Start of user code comment for kind setter
	 * End of user code -->
	 */
	public void setKind(String arg0){
		this.kind = arg0;
	}
	/*
	 * <!-- Start of user code comment for name getter
	 * End of user code -->
	 */
	public String getName(){
		return this.name;
	}
	
	/*
	 * <!-- Start of user code comment for name setter
	 * End of user code -->
	 */
	public void setName(String arg0){
		this.name = arg0;
	}
	/*
	 * <!-- Start of user code comment for risque getter
	 * End of user code -->
	 */
	public RisqueBean getRisque(){
		return this.risque;
	}
	
	/*
	 * <!-- Start of user code comment for risque setter
	 * End of user code -->
	 */
	public void setRisque(RisqueBean arg0){
		this.risque = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for risque unsetter
	 * End of user code -->
	 */
	public void unsetRisque(){
			this.risque = null;
			
	} 
	/*
	 * <!-- Start of user code comment for sample getter
	 * End of user code -->
	 */
	public SampleBean getSample(){
		return this.sample;
	}
	
	/*
	 * <!-- Start of user code comment for sample setter
	 * End of user code -->
	 */
	public void setSample(SampleBean arg0){
		this.sample = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for sample unsetter
	 * End of user code -->
	 */
	public void unsetSample(){
			if (this.sample == null) {
				return;
			}
			SampleBean oldsample = this.sample;
			this.sample = null;
			oldsample.unsetProject();
	} 
	/*
	 * <!-- Start of user code comment for updateDate getter
	 * End of user code -->
	 */
	public java.util.Date getUpdateDate(){
		return this.updateDate;
	}
	
	/*
	 * <!-- Start of user code comment for updateDate setter
	 * End of user code -->
	 */
	public void setUpdateDate(java.util.Date arg0){
		this.updateDate = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for updateDate unsetter
	 * End of user code -->
	 */
	public void unsetUpdateDate(java.util.Date arg0){
		this.updateDate = null;
	}
	/*
	 * <!-- Start of user code comment for version getter
	 * End of user code -->
	 */
	public int getVersion(){
		return this.version;
	}
	
	/*
	 * <!-- Start of user code comment for version setter
	 * End of user code -->
	 */
	public void setVersion(int arg0){
		this.version = arg0;
	}
    

	public Element toXML(){
		Element e = new Element("Project");
		if (uuid != null)
			e.setAttribute(new Attribute("uuid", uuid));
		if (getKind() != null)
			e.setAttribute(new Attribute("kind", getKind()));
		if (getDescription() != null)
			e.setAttribute(new Attribute("description", getDescription()));
		if (getName() != null)
			e.setAttribute(new Attribute("name", getName()));
		if (getStatus() != null)
			e.setAttribute(new Attribute("Status", getStatus()));
		e.setAttribute(new Attribute("id", String.valueOf(getId())));
		if (getCreationDate() != null)
			e.setAttribute(new Attribute("creationDate", getCreationDate().toString()));
		if (getUpdateDate() != null)
			e.setAttribute(new Attribute("updateDate", getUpdateDate().toString()));
		e.setAttribute(new Attribute("version", String.valueOf(getVersion())));
		
		if (getRisque() != null)
			e.setAttribute("risque", String.valueOf(getRisque().getId()));
		if (getSample() != null)
			e.setAttribute("sample", String.valueOf(getSample().getId()));
		if (getContacts() != null)
			e.setAttribute("contacts", String.valueOf(getContacts().getId()));
		if (getGazconfiguration() != null)
			e.setAttribute("gazconfiguration", String.valueOf(getGazconfiguration().getId()));
		if (getImage() != null)
			e.setAttribute("image", String.valueOf(getImage().getId()));
		
		return e;
	}

	//Start of user code for methods
	// Other methods
	//End of user code

}
