package com.genmymodel.petshop.entity;


//Start of user code for imports
// TODO: import me!
//End of user code

//
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.genmymodel.petshop.wrapper.Address;
import com.dooapp.lib.common.entity.Bean;

//Start of user code for queries
//End of user code

@javax.persistence.Entity
public class AddressBean implements Bean
{
	//Start of user code for attributes
	// Other attributes
	//End of user code

	/**
	 * The logger
	 */
	private static final Logger logger = LoggerFactory.getLogger(AddressBean.class);

	
	private String city;
	
	private String country;
	@javax.persistence.Column(name = "CREATION_DATE")
	@javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date creationDate;
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "seq", initialValue = 1, allocationSize = 10)
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.SEQUENCE, generator = "seq")
	@javax.persistence.Column(name = "ID")
	private long id;
	
	private String line1;
	
	private String line2;
	@javax.persistence.Column(name = "UPDATE_DATE")
	@javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date updateDate;
	@javax.persistence.Version
	@javax.persistence.Column(name = "VERSIONCOLUMN")
	private int version;

	@javax.persistence.Transient
	private Address wrapper;
    	
	/**
	 * The current UUID of this object.<br>
	 * It's generated by the JPA provider, so you do not have to do it yourself.<br>
	 * <br>
	 * 
	 * @see <a
	 *      href="http://openjpa.apache.org/builds/2.1.1/apache-openjpa-2.1.1/docs/jpa_overview_meta_field.html#jpa_overview_meta_gen">jpa
	 *      documentation</a>
	 * @see <a href="http://fr.wikipedia.org/wiki/UUID">wikipedia</a>
	 */
	@javax.persistence.Column(name = "UUID", columnDefinition = "CHAR(36)")
	private String uuid;
	@javax.persistence.Transient
	@Override
	public Address getWrapper() {
		if (wrapper == null) {
			wrapper = new Address(this);
		}
		return wrapper;
	}
	
	@javax.persistence.Transient
	@Override
	public boolean isWrapped() { 
		return wrapper != null;
	}
	
	@javax.persistence.Transient
	public void setWrapper(Address wrapper) {
		if (this.wrapper != null && this.wrapper != wrapper) {
			throw new RuntimeException("A bean can only have one wrapper, use #getWrapper instead");
		}
		this.wrapper = wrapper;
	}

	/**
	 * Configure date and identifiant when persisting the object the first time
	 */
	@javax.persistence.PrePersist
	void initDates() {
		updateDate = new java.util.Date();
		creationDate = new java.util.Date();
		if (uuid == null) {
			uuid = java.util.UUID.randomUUID().toString();
		}
	}
	
	/**
	 * Configure the update date when updating the object
	 */
	@javax.persistence.PreUpdate
	void initUpdateDate() {
		updateDate = new java.util.Date();
	}
	

	public String getCity(){
		return this.city;
	}
	
	public void setCity(String arg0){
		this.city = arg0;
	}
	public String getCountry(){
		return this.country;
	}
	
	public void setCountry(String arg0){
		this.country = arg0;
	}
	public java.util.Date getCreationDate(){
		return this.creationDate;
	}
	
	public void setCreationDate(java.util.Date arg0){
		this.creationDate = arg0;
	}
	
	public void unsetCreationDate(java.util.Date arg0){
		this.creationDate = null;
	}
	public long getId(){
		return this.id;
	}
	
	public void setId(long arg0){
		this.id = arg0;
	}
	public String getLine1(){
		return this.line1;
	}
	
	public void setLine1(String arg0){
		this.line1 = arg0;
	}
	public String getLine2(){
		return this.line2;
	}
	
	public void setLine2(String arg0){
		this.line2 = arg0;
	}
	public java.util.Date getUpdateDate(){
		return this.updateDate;
	}
	
	public void setUpdateDate(java.util.Date arg0){
		this.updateDate = arg0;
	}
	
	public void unsetUpdateDate(java.util.Date arg0){
		this.updateDate = null;
	}
	public int getVersion(){
		return this.version;
	}
	
	public void setVersion(int arg0){
		this.version = arg0;
	}
    


	//Start of user code for methods
	// Other methods
	//End of user code

}
