package com.genmymodel.petshop.entity;


//Start of user code for imports
// TODO: import me!
//End of user code

//
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.genmymodel.petshop.wrapper.Customer;
import com.dooapp.lib.common.entity.Bean;

//Start of user code for queries
//End of user code

@javax.persistence.Entity
public class CustomerBean implements Bean
{
	//Start of user code for attributes
	// Other attributes
	//End of user code

	/**
	 * The logger
	 */
	private static final Logger logger = LoggerFactory.getLogger(CustomerBean.class);

	
	@javax.persistence.ManyToOne(cascade = javax.persistence.CascadeType.ALL)
	private AddressBean address;
	
	@javax.persistence.OneToOne(optional = true, cascade = javax.persistence.CascadeType.ALL)
	private CartBean carts;
	@javax.persistence.Column(name = "CREATION_DATE")
	@javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date creationDate;
	
	private String firstName;
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "seq", initialValue = 1, allocationSize = 10)
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.SEQUENCE, generator = "seq")
	@javax.persistence.Column(name = "ID")
	private long id;
	
	private String lastName;
	
	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, mappedBy = "customer", cascade = javax.persistence.CascadeType.ALL)
	private java.util.Set<OrderBean> orders;
	@javax.persistence.Column(name = "UPDATE_DATE")
	@javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date updateDate;
	@javax.persistence.Version
	@javax.persistence.Column(name = "VERSIONCOLUMN")
	private int version;

	@javax.persistence.Transient
	private Customer wrapper;
    	
	/**
	 * The current UUID of this object.<br>
	 * It's generated by the JPA provider, so you do not have to do it yourself.<br>
	 * <br>
	 * 
	 * @see <a
	 *      href="http://openjpa.apache.org/builds/2.1.1/apache-openjpa-2.1.1/docs/jpa_overview_meta_field.html#jpa_overview_meta_gen">jpa
	 *      documentation</a>
	 * @see <a href="http://fr.wikipedia.org/wiki/UUID">wikipedia</a>
	 */
	@javax.persistence.Column(name = "UUID", columnDefinition = "CHAR(36)")
	private String uuid;
	@javax.persistence.Transient
	@Override
	public Customer getWrapper() {
		if (wrapper == null) {
			wrapper = new Customer(this);
		}
		return wrapper;
	}
	
	@javax.persistence.Transient
	@Override
	public boolean isWrapped() { 
		return wrapper != null;
	}
	
	@javax.persistence.Transient
	public void setWrapper(Customer wrapper) {
		if (this.wrapper != null && this.wrapper != wrapper) {
			throw new RuntimeException("A bean can only have one wrapper, use #getWrapper instead");
		}
		this.wrapper = wrapper;
	}

	/**
	 * Configure date and identifiant when persisting the object the first time
	 */
	@javax.persistence.PrePersist
	void initDates() {
		updateDate = new java.util.Date();
		creationDate = new java.util.Date();
		if (uuid == null) {
			uuid = java.util.UUID.randomUUID().toString();
		}
	}
	
	/**
	 * Configure the update date when updating the object
	 */
	@javax.persistence.PreUpdate
	void initUpdateDate() {
		updateDate = new java.util.Date();
	}
	

	public AddressBean getAddress(){
		return this.address;
	}
	
	public void setAddress(AddressBean arg0){
		this.address = arg0;
	}
	
	public void unsetAddress(){
			this.address = null;
			
	} 
	public CartBean getCarts(){
		return this.carts;
	}
	
	public void setCarts(CartBean arg0){
		this.carts = arg0;
	}
	
	public void unsetCarts(){
			if (this.carts == null) {
				return;
			}
			CartBean oldcarts = this.carts;
			this.carts = null;
			oldcarts.unsetCustomer();
	} 
	public java.util.Date getCreationDate(){
		return this.creationDate;
	}
	
	public void setCreationDate(java.util.Date arg0){
		this.creationDate = arg0;
	}
	
	public void unsetCreationDate(java.util.Date arg0){
		this.creationDate = null;
	}
	public String getFirstName(){
		return this.firstName;
	}
	
	public void setFirstName(String arg0){
		this.firstName = arg0;
	}
	public long getId(){
		return this.id;
	}
	
	public void setId(long arg0){
		this.id = arg0;
	}
	public String getLastName(){
		return this.lastName;
	}
	
	public void setLastName(String arg0){
		this.lastName = arg0;
	}
	public java.util.List<OrderBean> getOrders(){
			if(this.orders==null) {
				this.orders= new java.util.HashSet<OrderBean>();
			}
			return new java.util.ArrayList<OrderBean>(this.orders);
	}
	
	public void addOrders(OrderBean newOrders){
		if(this.orders==null) {
				this.orders= new java.util.HashSet<OrderBean>();
			}
				
			this.orders.add (newOrders);
	} 
	public java.util.Date getUpdateDate(){
		return this.updateDate;
	}
	
	public void setUpdateDate(java.util.Date arg0){
		this.updateDate = arg0;
	}
	
	public void unsetUpdateDate(java.util.Date arg0){
		this.updateDate = null;
	}
	public int getVersion(){
		return this.version;
	}
	
	public void setVersion(int arg0){
		this.version = arg0;
	}
    


	//Start of user code for methods
	// Other methods
	//End of user code

}
