package com.genmymodel.petshop.entity;


//Start of user code for imports
// TODO: import me!
//End of user code

//
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.genmymodel.petshop.wrapper.Order;
import com.dooapp.lib.common.entity.Bean;

//Start of user code for queries
//End of user code
@javax.persistence.Entity
@javax.persistence.Table(name = "ORDERTABLE")
public class OrderBean implements Bean
{
	//Start of user code for attributes
	// Other attributes
	//End of user code

	/**
	 * The logger
	 */
	private static final Logger logger = LoggerFactory.getLogger(OrderBean.class);

	@javax.persistence.OneToOne(optional = true, cascade = javax.persistence.CascadeType.ALL)
	private CartBean cart;
	@javax.persistence.Column(name = "CREATION_DATE")
	@javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date creationDate;
	@javax.persistence.ManyToOne(cascade = javax.persistence.CascadeType.ALL)
	private CustomerBean customer;
	@javax.persistence.Column(name = "DATECOLUMN")
	private String date;
	@javax.persistence.ManyToOne(cascade = javax.persistence.CascadeType.ALL)
	private AddressBean deliveryAddress;
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "seq", initialValue = 1, allocationSize = 10)
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.SEQUENCE, generator = "seq")
	@javax.persistence.Column(name = "ID")
	private long id;
	@javax.persistence.ManyToMany(cascade = javax.persistence.CascadeType.ALL, fetch = javax.persistence.FetchType.EAGER)
	@javax.persistence.JoinTable(name = "ORDER_ITEMS")
	private java.util.Set<ItemBean> items;
	@javax.persistence.ManyToOne(cascade = javax.persistence.CascadeType.ALL)
	private AddressBean paymentAddress;
	
	private String reference;
	@javax.persistence.Enumerated(javax.persistence.EnumType.STRING)
	private com.genmymodel.petshop.entity.OrderStatus status;
	@javax.persistence.Column(name = "UPDATE_DATE")
	@javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date updateDate;
	@javax.persistence.Version
	@javax.persistence.Column(name = "VERSIONCOLUMN")
	private int version;

	@javax.persistence.Transient
	private Order wrapper;
    	
	/**
	 * The current UUID of this object.<br>
	 * It's generated by the JPA provider, so you do not have to do it yourself.<br>
	 * <br>
	 * 
	 * @see <a
	 *      href="http://openjpa.apache.org/builds/2.1.1/apache-openjpa-2.1.1/docs/jpa_overview_meta_field.html#jpa_overview_meta_gen">jpa
	 *      documentation</a>
	 * @see <a href="http://fr.wikipedia.org/wiki/UUID">wikipedia</a>
	 */
	@javax.persistence.Column(name = "UUID", columnDefinition = "CHAR(36)")
	private String uuid;
	@javax.persistence.Transient
	@Override
	public Order getWrapper() {
		if (wrapper == null) {
			wrapper = new Order(this);
		}
		return wrapper;
	}
	
	@javax.persistence.Transient
	@Override
	public boolean isWrapped() { 
		return wrapper != null;
	}
	
	@javax.persistence.Transient
	public void setWrapper(Order wrapper) {
		if (this.wrapper != null && this.wrapper != wrapper) {
			throw new RuntimeException("A bean can only have one wrapper, use #getWrapper instead");
		}
		this.wrapper = wrapper;
	}

	/**
	 * Configure date and identifiant when persisting the object the first time
	 */
	@javax.persistence.PrePersist
	void initDates() {
		updateDate = new java.util.Date();
		creationDate = new java.util.Date();
		if (uuid == null) {
			uuid = java.util.UUID.randomUUID().toString();
		}
	}
	
	/**
	 * Configure the update date when updating the object
	 */
	@javax.persistence.PreUpdate
	void initUpdateDate() {
		updateDate = new java.util.Date();
	}
	

	public CartBean getCart(){
		return this.cart;
	}
	
	public void setCart(CartBean arg0){
		this.cart = arg0;
	}
	
	public void unsetCart(){
			if (this.cart == null) {
				return;
			}
			CartBean oldcart = this.cart;
			this.cart = null;
			oldcart.unsetOrder();
	} 
	public java.util.Date getCreationDate(){
		return this.creationDate;
	}
	
	public void setCreationDate(java.util.Date arg0){
		this.creationDate = arg0;
	}
	
	public void unsetCreationDate(java.util.Date arg0){
		this.creationDate = null;
	}
	public CustomerBean getCustomer(){
		return this.customer;
	}
	
	public void setCustomer(CustomerBean arg0){
		this.customer = arg0;
	}
	
	public void unsetCustomer(){
			this.customer = null;
			
	} 
	public String getDate(){
		return this.date;
	}
	
	public void setDate(String arg0){
		this.date = arg0;
	}
	public AddressBean getDeliveryAddress(){
		return this.deliveryAddress;
	}
	
	public void setDeliveryAddress(AddressBean arg0){
		this.deliveryAddress = arg0;
	}
	
	public void unsetDeliveryAddress(){
			this.deliveryAddress = null;
			
	} 
	public long getId(){
		return this.id;
	}
	
	public void setId(long arg0){
		this.id = arg0;
	}
	public java.util.List<ItemBean> getItems(){
			if(this.items==null) {
				this.items= new java.util.HashSet<ItemBean>();
			}
			return new java.util.ArrayList<ItemBean>(this.items);
	}
	
	public void addItems(ItemBean newItems){
		if(this.items==null) {
				this.items= new java.util.HashSet<ItemBean>();
			}
				
			this.items.add (newItems);
	} 
	public AddressBean getPaymentAddress(){
		return this.paymentAddress;
	}
	
	public void setPaymentAddress(AddressBean arg0){
		this.paymentAddress = arg0;
	}
	
	public void unsetPaymentAddress(){
			this.paymentAddress = null;
			
	} 
	public String getReference(){
		return this.reference;
	}
	
	public void setReference(String arg0){
		this.reference = arg0;
	}
	public com.genmymodel.petshop.entity.OrderStatus getStatus(){
		return this.status;
	}
	
	public void setStatus(com.genmymodel.petshop.entity.OrderStatus arg0){
		this.status = arg0;
	}
	
	public void unsetStatus(com.genmymodel.petshop.entity.OrderStatus arg0){
		this.status = null;
	}
	public java.util.Date getUpdateDate(){
		return this.updateDate;
	}
	
	public void setUpdateDate(java.util.Date arg0){
		this.updateDate = arg0;
	}
	
	public void unsetUpdateDate(java.util.Date arg0){
		this.updateDate = null;
	}
	public int getVersion(){
		return this.version;
	}
	
	public void setVersion(int arg0){
		this.version = arg0;
	}
    


	//Start of user code for methods
	// Other methods
	//End of user code

}
