package com.dooapp.firea.entity;


//Start of user code for imports
// TODO: import me!
//End of user code

//
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.dooapp.firea.wrapper.Project;
import com.dooapp.lib.common.entity.Bean;

//Start of user code for queries
//End of user code
@javax.persistence.Entity
public class ProjectBean implements Bean
{
	//Start of user code for attributes
	// Other attributes
	//End of user code

	/**
	 * The logger
	 */
	private static final Logger logger = LoggerFactory.getLogger(ProjectBean.class);

	@javax.persistence.Enumerated(javax.persistence.EnumType.STRING)
	private com.dooapp.firea.entity.ProjectKind Status;
	@javax.persistence.ManyToMany(cascade = javax.persistence.CascadeType.ALL, fetch = javax.persistence.FetchType.EAGER)
	@javax.persistence.JoinTable(name = "PROJECT_CONTACTS")
	private java.util.Set<ContactBean> contacts;
	@javax.persistence.Column(name = "CREATION_DATE")
	@javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date creationDate;
	
	private String description;
	@javax.persistence.OneToOne(optional = false, cascade = javax.persistence.CascadeType.ALL)
	private GazConfigurationBean gazconfiguration;
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "seq", initialValue = 1, allocationSize = 10)
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.SEQUENCE, generator = "seq")
	@javax.persistence.Column(name = "ID")
	private long id;
	@javax.persistence.ManyToOne(cascade = javax.persistence.CascadeType.ALL)
	private PersistentImageBean image;
	@javax.persistence.Enumerated(javax.persistence.EnumType.STRING)
	private com.dooapp.firea.entity.ProjectKind kind;
	@javax.persistence.Column(name = "NAMECOLUMN")
	private String name;
	@javax.persistence.ManyToOne(cascade = javax.persistence.CascadeType.ALL)
	private RisqueBean risque;
	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, mappedBy = "project", cascade = javax.persistence.CascadeType.ALL)
	private java.util.Set<SampleBean> sample;
	@javax.persistence.Column(name = "UPDATE_DATE")
	@javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date updateDate;
	@javax.persistence.Version
	@javax.persistence.Column(name = "VERSIONCOLUMN")
	private int version;

	@javax.persistence.Transient
	private Project wrapper;
    	
	/**
	 * The current UUID of this object.<br>
	 * It's generated by the JPA provider, so you do not have to do it yourself.<br>
	 * <br>
	 * 
	 * @see <a
	 *      href="http://openjpa.apache.org/builds/2.1.1/apache-openjpa-2.1.1/docs/jpa_overview_meta_field.html#jpa_overview_meta_gen">jpa
	 *      documentation</a>
	 * @see <a href="http://fr.wikipedia.org/wiki/UUID">wikipedia</a>
	 */
	@javax.persistence.Column(name = "UUID", columnDefinition = "CHAR(36)")
	private String uuid;
	@javax.persistence.Transient
	@Override
	public Project getWrapper() {
		if (wrapper == null) {
			wrapper = new Project(this);
		}
		return wrapper;
	}
	
	@javax.persistence.Transient
	@Override
	public boolean isWrapped() { 
		return wrapper != null;
	}
	
	@javax.persistence.Transient
	public void setWrapper(Project wrapper) {
		if (this.wrapper != null && this.wrapper != wrapper) {
			throw new RuntimeException("A bean can only have one wrapper, use #getWrapper instead");
		}
		this.wrapper = wrapper;
	}

	/**
	 * Configure date and identifiant when persisting the object the first time
	 */
	@javax.persistence.PrePersist
	void initDates() {
		updateDate = new java.util.Date();
		creationDate = new java.util.Date();
		if (uuid == null) {
			uuid = java.util.UUID.randomUUID().toString();
		}
	}
	
	/**
	 * Configure the update date when updating the object
	 */
	@javax.persistence.PreUpdate
	void initUpdateDate() {
		updateDate = new java.util.Date();
	}
	

	public com.dooapp.firea.entity.ProjectKind getStatus(){
		return this.Status;
	}
	
	public void setStatus(com.dooapp.firea.entity.ProjectKind arg0){
		this.Status = arg0;
	}
	
	public void unsetStatus(com.dooapp.firea.entity.ProjectKind arg0){
		this.Status = null;
	}
	public java.util.List<ContactBean> getContacts(){
			if(this.contacts==null) {
				this.contacts= new java.util.HashSet<ContactBean>();
			}
			return new java.util.ArrayList<ContactBean>(this.contacts);
	}
	
	public void addContacts(ContactBean newContacts){
		if(this.contacts==null) {
				this.contacts= new java.util.HashSet<ContactBean>();
			}
				
			this.contacts.add (newContacts);
	} 
	public java.util.Date getCreationDate(){
		return this.creationDate;
	}
	
	public void setCreationDate(java.util.Date arg0){
		this.creationDate = arg0;
	}
	
	public void unsetCreationDate(java.util.Date arg0){
		this.creationDate = null;
	}
	public String getDescription(){
		return this.description;
	}
	
	public void setDescription(String arg0){
		this.description = arg0;
	}
	public GazConfigurationBean getGazconfiguration(){
		return this.gazconfiguration;
	}
	
	public void setGazconfiguration(GazConfigurationBean arg0){
		this.gazconfiguration = arg0;
	}
	
	public void unsetGazconfiguration(){
			if (this.gazconfiguration == null) {
				return;
			}
			GazConfigurationBean oldgazconfiguration = this.gazconfiguration;
			this.gazconfiguration = null;
			oldgazconfiguration.unsetProject();
	} 
	public long getId(){
		return this.id;
	}
	
	public void setId(long arg0){
		this.id = arg0;
	}
	public PersistentImageBean getImage(){
		return this.image;
	}
	
	public void setImage(PersistentImageBean arg0){
		this.image = arg0;
	}
	
	public void unsetImage(){
			this.image = null;
			
	} 
	public com.dooapp.firea.entity.ProjectKind getKind(){
		return this.kind;
	}
	
	public void setKind(com.dooapp.firea.entity.ProjectKind arg0){
		this.kind = arg0;
	}
	
	public void unsetKind(com.dooapp.firea.entity.ProjectKind arg0){
		this.kind = null;
	}
	public String getName(){
		return this.name;
	}
	
	public void setName(String arg0){
		this.name = arg0;
	}
	public RisqueBean getRisque(){
		return this.risque;
	}
	
	public void setRisque(RisqueBean arg0){
		this.risque = arg0;
	}
	
	public void unsetRisque(){
			this.risque = null;
			
	} 
	public java.util.List<SampleBean> getSample(){
			if(this.sample==null) {
				this.sample= new java.util.HashSet<SampleBean>();
			}
			return new java.util.ArrayList<SampleBean>(this.sample);
	}
	
	public void addSample(SampleBean newSample){
		if(this.sample==null) {
				this.sample= new java.util.HashSet<SampleBean>();
			}
				
			this.sample.add (newSample);
	} 
	public java.util.Date getUpdateDate(){
		return this.updateDate;
	}
	
	public void setUpdateDate(java.util.Date arg0){
		this.updateDate = arg0;
	}
	
	public void unsetUpdateDate(java.util.Date arg0){
		this.updateDate = null;
	}
	public int getVersion(){
		return this.version;
	}
	
	public void setVersion(int arg0){
		this.version = arg0;
	}
    


	//Start of user code for methods
	// Other methods
	//End of user code

}
