package com.genmymodel.petshop.entity;

import org.jdom2.Attribute;
import org.jdom2.Element;

//Start of user code for imports
// TODO: import me!
//End of user code


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.genmymodel.petshop.wrapper.Cart;
import com.dooapp.lib.common.entity.Bean;


/*
 * Class
 * <!-- Start of user code comment for Cart Class
 * End of user code -->
 */
//Start of user code for queries
//End of user code

@javax.persistence.Entity
public class CartBean
//Start of user code bloc for inheritance

//End of user code
//Start of user code bloc for interfaces
 implements Bean
//End of user code
{
	//Start of user code for attributes
	// Other attributes
	//End of user code

	/**
	 * The logger
	 */
	private static final Logger logger = LoggerFactory.getLogger(CartBean.class);

	
	/**
	 *  
	 */
	private java.util.Date creationDate;


	/**
	 *  
	 */
	private java.util.Date creationDate;


	/**
	 *  
	 */
	private java.util.Date creationDate;
	@javax.persistence.Column(name = "CREATION_DATE")
	@javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date creationDate;
	
	@javax.persistence.OneToOne(optional = false, cascade = javax.persistence.CascadeType.ALL, mappedBy = "carts")
	private CustomerBean customer;
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "seq", initialValue = 1, allocationSize = 10)
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.SEQUENCE, generator = "seq")
	@javax.persistence.Column(name = "ID")
	private long id;
	
	@javax.persistence.ManyToMany(cascade = javax.persistence.CascadeType.ALL, fetch = javax.persistence.FetchType.EAGER)
	@javax.persistence.JoinTable(name = "CART_ITEMS")
	private java.util.Set<ItemBean> items;
	
	@javax.persistence.OneToOne(optional = true, cascade = javax.persistence.CascadeType.ALL, mappedBy = "cart")
	private OrderBean order;
	@javax.persistence.Column(name = "UPDATE_DATE")
	@javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date updateDate;
	@javax.persistence.Version
	@javax.persistence.Column(name = "VERSIONCOLUMN")
	private int version;

	@javax.persistence.Transient
	private Cart wrapper;
    	
	/**
	 * The current UUID of this object.<br>
	 * It's generated by the JPA provider, so you do not have to do it yourself.<br>
	 * <br>
	 * 
	 * @see <a
	 *      href="http://openjpa.apache.org/builds/2.1.1/apache-openjpa-2.1.1/docs/jpa_overview_meta_field.html#jpa_overview_meta_gen">jpa
	 *      documentation</a>
	 * @see <a href="http://fr.wikipedia.org/wiki/UUID">wikipedia</a>
	 */
	@javax.persistence.Column(name = "UUID", columnDefinition = "CHAR(36)")
	protected String uuid;
	/*
	 * <!-- Start of user code comment for Cart wrapper getter
	 * End of user code -->
	 */
	@javax.persistence.Transient
	@Override
	public Cart getWrapper() {
		if (wrapper == null) {
			wrapper = new Cart(this);
		}
		return wrapper;
	}
	
	@javax.persistence.Transient
	@Override
	public boolean isWrapped() { 
		return wrapper != null;
	}
	
	/*
	 * <!-- Start of user code comment for Cart wrapper setter
	 * End of user code -->
	 */
	@javax.persistence.Transient
	public void setWrapper(Cart wrapper) {
		if (this.wrapper != null && this.wrapper != wrapper) {
			throw new RuntimeException("A bean can only have one wrapper, use #getWrapper instead");
		}
		this.wrapper = wrapper;
	}

	/**
	 * Configure date and identifiant when persisting the object the first time
	 */
	@javax.persistence.PrePersist
	void initDates() {
		updateDate = new java.util.Date();
		creationDate = new java.util.Date();
		if (uuid == null) {
			uuid = java.util.UUID.randomUUID().toString();
		}
	}
	
	/**
	 * Configure the update date when updating the object
	 */
	@javax.persistence.PreUpdate
	void initUpdateDate() {
		updateDate = new java.util.Date();
	}
	

	public java.util.Date getCreationDate(){
		return this.creationDate;
	}

	public void setCreationDate(java.util.Date arg0){
		this.creationDate = arg0;
	}

	public void unsetCreationDate(java.util.Date arg0){
		this.creationDate = null;
	}

	public java.util.Date getCreationDate(){
		return this.creationDate;
	}

	public void setCreationDate(java.util.Date arg0){
		this.creationDate = arg0;
	}

	public void unsetCreationDate(java.util.Date arg0){
		this.creationDate = null;
	}

	/*
	 * <!-- Start of user code comment for creationDate getter
	 * End of user code -->
	 */
	public java.util.Date getCreationDate(){
		return this.creationDate;
	}
	
	/*
	 * <!-- Start of user code comment for creationDate setter
	 * End of user code -->
	 */
	public void setCreationDate(java.util.Date arg0){
		this.creationDate = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for creationDate unsetter
	 * End of user code -->
	 */
	public void unsetCreationDate(java.util.Date arg0){
		this.creationDate = null;
	}
	/*
	 * <!-- Start of user code comment for creationDate getter
	 * End of user code -->
	 */
	public java.util.Date getCreationDate(){
		return this.creationDate;
	}
	
	/*
	 * <!-- Start of user code comment for creationDate setter
	 * End of user code -->
	 */
	public void setCreationDate(java.util.Date arg0){
		this.creationDate = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for creationDate unsetter
	 * End of user code -->
	 */
	public void unsetCreationDate(java.util.Date arg0){
		this.creationDate = null;
	}
	/*
	 * <!-- Start of user code comment for customer getter
	 * End of user code -->
	 */
	public CustomerBean getCustomer(){
		return this.customer;
	}
	
	/*
	 * <!-- Start of user code comment for customer setter
	 * End of user code -->
	 */
	public void setCustomer(CustomerBean arg0){
		this.customer = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for customer unsetter
	 * End of user code -->
	 */
	public void unsetCustomer(){
			if (this.customer == null) {
				return;
			}
			CustomerBean oldcustomer = this.customer;
			this.customer = null;
			oldcustomer.unsetCarts();
	} 
	/*
	 * <!-- Start of user code comment for id getter
	 * End of user code -->
	 */
	public long getId(){
		return this.id;
	}
	
	/*
	 * <!-- Start of user code comment for id setter
	 * End of user code -->
	 */
	public void setId(long arg0){
		this.id = arg0;
	}
	/*
	 * <!-- Start of user code comment for items getter
	 * End of user code -->
	 */
	public java.util.List<ItemBean> getItems(){
			if(this.items==null) {
				this.items= new java.util.HashSet<ItemBean>();
			}
			return new java.util.ArrayList<ItemBean>(this.items);
	}
	
	/*
	 * <!-- Start of user code comment for items adder
	 * End of user code -->
	 */
	public void addItems(ItemBean newItems){
		if(this.items==null) {
				this.items= new java.util.HashSet<ItemBean>();
			}
				
			this.items.add (newItems);
	} 
	/*
	 * <!-- Start of user code comment for order getter
	 * End of user code -->
	 */
	public OrderBean getOrder(){
		return this.order;
	}
	
	/*
	 * <!-- Start of user code comment for order setter
	 * End of user code -->
	 */
	public void setOrder(OrderBean arg0){
		this.order = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for order unsetter
	 * End of user code -->
	 */
	public void unsetOrder(){
			if (this.order == null) {
				return;
			}
			OrderBean oldorder = this.order;
			this.order = null;
			oldorder.unsetCart();
	} 
	/*
	 * <!-- Start of user code comment for updateDate getter
	 * End of user code -->
	 */
	public java.util.Date getUpdateDate(){
		return this.updateDate;
	}
	
	/*
	 * <!-- Start of user code comment for updateDate setter
	 * End of user code -->
	 */
	public void setUpdateDate(java.util.Date arg0){
		this.updateDate = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for updateDate unsetter
	 * End of user code -->
	 */
	public void unsetUpdateDate(java.util.Date arg0){
		this.updateDate = null;
	}
	/*
	 * <!-- Start of user code comment for version getter
	 * End of user code -->
	 */
	public int getVersion(){
		return this.version;
	}
	
	/*
	 * <!-- Start of user code comment for version setter
	 * End of user code -->
	 */
	public void setVersion(int arg0){
		this.version = arg0;
	}
    

	public Element toXML(){
		Element xmlElement = new Element("Cart");
		if (uuid != null)
			xmlElement.setAttribute(new Attribute("uuid", uuid));
		if (getCreationDate() != null)
			xmlElement.setAttribute(new Attribute("creationDate", getCreationDate().toString()));
		xmlElement.setAttribute(new Attribute("id", String.valueOf(getId())));
		if (getCreationDate() != null)
			xmlElement.setAttribute(new Attribute("creationDate", getCreationDate().toString()));
		if (getUpdateDate() != null)
			xmlElement.setAttribute(new Attribute("updateDate", getUpdateDate().toString()));
		xmlElement.setAttribute(new Attribute("version", String.valueOf(getVersion())));
		
		if (!getItems().isEmpty()) {
			Element items = new Element("items");
			for (ItemBean tmp : getItems())
				items.addContent(tmp.toXML());
			xmlElement.addContent(items);
		}
		if (getCustomer() != null)
			xmlElement.setAttribute("customer", String.valueOf(getCustomer().getId()));
		if (getOrder() != null)
			xmlElement.setAttribute("order", String.valueOf(getOrder().getId()));
		
		return xmlElement;
	}

	//Start of user code for methods
	// Other methods
	//End of user code

}
