package com.genmymodel.petshop.entity;

import org.jdom2.Attribute;
import org.jdom2.Element;

//Start of user code for imports
// TODO: import me!
//End of user code


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.genmymodel.petshop.wrapper.Customer;
import com.dooapp.lib.common.entity.Bean;


/*
 * Class
 * <!-- Start of user code comment for Customer Class
 * End of user code -->
 */
//Start of user code for queries
//End of user code

/**
 *  
 */
@javax.persistence.Entity
public class CustomerBean
//Start of user code bloc for inheritance

//End of user code
//Start of user code bloc for interfaces
 implements Bean
//End of user code
{
	//Start of user code for attributes
	// Other attributes
	//End of user code

	/**
	 * The logger
	 */
	private static final Logger logger = LoggerFactory.getLogger(CustomerBean.class);

	
	@javax.persistence.ManyToOne(cascade = javax.persistence.CascadeType.ALL)
	private AddressBean address;
	
	@javax.persistence.OneToOne(optional = true, cascade = javax.persistence.CascadeType.ALL)
	private CartBean carts;
	@javax.persistence.Column(name = "CREATION_DATE")
	@javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date creationDate;
	
	/**
	 *  
	 */
	private String firstName;
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "seq", initialValue = 1, allocationSize = 10)
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.SEQUENCE, generator = "seq")
	@javax.persistence.Column(name = "ID")
	private long id;
	
	/**
	 *  
	 */
	private String lastName;
	
	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, mappedBy = "customer", cascade = javax.persistence.CascadeType.ALL)
	private java.util.Set<OrderBean> orders;
	@javax.persistence.Column(name = "UPDATE_DATE")
	@javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date updateDate;
	@javax.persistence.Version
	@javax.persistence.Column(name = "VERSIONCOLUMN")
	private int version;

	@javax.persistence.Transient
	private Customer wrapper;
    	
	/**
	 * The current UUID of this object.<br>
	 * It's generated by the JPA provider, so you do not have to do it yourself.<br>
	 * <br>
	 * 
	 * @see <a
	 *      href="http://openjpa.apache.org/builds/2.1.1/apache-openjpa-2.1.1/docs/jpa_overview_meta_field.html#jpa_overview_meta_gen">jpa
	 *      documentation</a>
	 * @see <a href="http://fr.wikipedia.org/wiki/UUID">wikipedia</a>
	 */
	@javax.persistence.Column(name = "UUID", columnDefinition = "CHAR(36)")
	protected String uuid;
	/*
	 * <!-- Start of user code comment for Customer wrapper getter
	 * End of user code -->
	 */
	@javax.persistence.Transient
	@Override
	public Customer getWrapper() {
		if (wrapper == null) {
			wrapper = new Customer(this);
		}
		return wrapper;
	}
	
	@javax.persistence.Transient
	@Override
	public boolean isWrapped() { 
		return wrapper != null;
	}
	
	/*
	 * <!-- Start of user code comment for Customer wrapper setter
	 * End of user code -->
	 */
	@javax.persistence.Transient
	public void setWrapper(Customer wrapper) {
		if (this.wrapper != null && this.wrapper != wrapper) {
			throw new RuntimeException("A bean can only have one wrapper, use #getWrapper instead");
		}
		this.wrapper = wrapper;
	}

	/**
	 * Configure date and identifiant when persisting the object the first time
	 */
	@javax.persistence.PrePersist
	void initDates() {
		updateDate = new java.util.Date();
		creationDate = new java.util.Date();
		if (uuid == null) {
			uuid = java.util.UUID.randomUUID().toString();
		}
	}
	
	/**
	 * Configure the update date when updating the object
	 */
	@javax.persistence.PreUpdate
	void initUpdateDate() {
		updateDate = new java.util.Date();
	}
	

	/*
	 * <!-- Start of user code comment for address getter
	 * End of user code -->
	 */
	public AddressBean getAddress(){
		return this.address;
	}
	
	/*
	 * <!-- Start of user code comment for address setter
	 * End of user code -->
	 */
	public void setAddress(AddressBean arg0){
		this.address = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for address unsetter
	 * End of user code -->
	 */
	public void unsetAddress(){
			this.address = null;
			
	} 
	/*
	 * <!-- Start of user code comment for carts getter
	 * End of user code -->
	 */
	public CartBean getCarts(){
		return this.carts;
	}
	
	/*
	 * <!-- Start of user code comment for carts setter
	 * End of user code -->
	 */
	public void setCarts(CartBean arg0){
		this.carts = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for carts unsetter
	 * End of user code -->
	 */
	public void unsetCarts(){
			if (this.carts == null) {
				return;
			}
			CartBean oldcarts = this.carts;
			this.carts = null;
			oldcarts.unsetCustomer();
	} 
	/*
	 * <!-- Start of user code comment for creationDate getter
	 * End of user code -->
	 */
	public java.util.Date getCreationDate(){
		return this.creationDate;
	}
	
	/*
	 * <!-- Start of user code comment for creationDate setter
	 * End of user code -->
	 */
	public void setCreationDate(java.util.Date arg0){
		this.creationDate = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for creationDate unsetter
	 * End of user code -->
	 */
	public void unsetCreationDate(java.util.Date arg0){
		this.creationDate = null;
	}
	/*
	 * <!-- Start of user code comment for firstName getter
	 * End of user code -->
	 */
	public String getFirstName(){
		return this.firstName;
	}
	
	/*
	 * <!-- Start of user code comment for firstName setter
	 * End of user code -->
	 */
	public void setFirstName(String arg0){
		this.firstName = arg0;
	}
	/*
	 * <!-- Start of user code comment for id getter
	 * End of user code -->
	 */
	public long getId(){
		return this.id;
	}
	
	/*
	 * <!-- Start of user code comment for id setter
	 * End of user code -->
	 */
	public void setId(long arg0){
		this.id = arg0;
	}
	/*
	 * <!-- Start of user code comment for lastName getter
	 * End of user code -->
	 */
	public String getLastName(){
		return this.lastName;
	}
	
	/*
	 * <!-- Start of user code comment for lastName setter
	 * End of user code -->
	 */
	public void setLastName(String arg0){
		this.lastName = arg0;
	}
	/*
	 * <!-- Start of user code comment for orders getter
	 * End of user code -->
	 */
	public java.util.List<OrderBean> getOrders(){
			if(this.orders==null) {
				this.orders= new java.util.HashSet<OrderBean>();
			}
			return new java.util.ArrayList<OrderBean>(this.orders);
	}
	
	/*
	 * <!-- Start of user code comment for orders adder
	 * End of user code -->
	 */
	public void addOrders(OrderBean newOrders){
		if(this.orders==null) {
				this.orders= new java.util.HashSet<OrderBean>();
			}
				
			this.orders.add (newOrders);
	} 
	/*
	 * <!-- Start of user code comment for updateDate getter
	 * End of user code -->
	 */
	public java.util.Date getUpdateDate(){
		return this.updateDate;
	}
	
	/*
	 * <!-- Start of user code comment for updateDate setter
	 * End of user code -->
	 */
	public void setUpdateDate(java.util.Date arg0){
		this.updateDate = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for updateDate unsetter
	 * End of user code -->
	 */
	public void unsetUpdateDate(java.util.Date arg0){
		this.updateDate = null;
	}
	/*
	 * <!-- Start of user code comment for version getter
	 * End of user code -->
	 */
	public int getVersion(){
		return this.version;
	}
	
	/*
	 * <!-- Start of user code comment for version setter
	 * End of user code -->
	 */
	public void setVersion(int arg0){
		this.version = arg0;
	}
    

	public Element toXML(){
		Element xmlElement = new Element("Customer");
		if (uuid != null)
			xmlElement.setAttribute(new Attribute("uuid", uuid));
		if (getLastName() != null)
			xmlElement.setAttribute(new Attribute("lastName", getLastName()));
		if (getFirstName() != null)
			xmlElement.setAttribute(new Attribute("firstName", getFirstName()));
		xmlElement.setAttribute(new Attribute("id", String.valueOf(getId())));
		if (getCreationDate() != null)
			xmlElement.setAttribute(new Attribute("creationDate", getCreationDate().toString()));
		if (getUpdateDate() != null)
			xmlElement.setAttribute(new Attribute("updateDate", getUpdateDate().toString()));
		xmlElement.setAttribute(new Attribute("version", String.valueOf(getVersion())));
		
		if (!getOrders().isEmpty()) {
			Element orders = new Element("orders");
			for (OrderBean tmp : getOrders())
				orders.addContent(tmp.toXML());
			xmlElement.addContent(orders);
		}
		if (getAddress() != null) {
			Element address = new Element("address");
			address.addContent(getAddress().toXML());
			xmlElement.addContent(address);
		}if (getCarts() != null) {
			Element carts = new Element("carts");
			carts.addContent(getCarts().toXML());
			xmlElement.addContent(carts);
		}
		return xmlElement;
	}

	//Start of user code for methods
	// Other methods
	//End of user code

}
