package com.genmymodel.petshop.entity;

import org.jdom2.Attribute;
import org.jdom2.Element;

//Start of user code for imports
// TODO: import me!
//End of user code


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.genmymodel.petshop.wrapper.Order;
import com.dooapp.lib.common.entity.Bean;


/*
 * Class
 * <!-- Start of user code comment for Order Class
 * End of user code -->
 */
//Start of user code for queries
//End of user code

@javax.persistence.Entity
@javax.persistence.Table(name = "ORDERTABLE")
public class OrderBean
//Start of user code bloc for inheritance

//End of user code
//Start of user code bloc for interfaces
 implements Bean
//End of user code
{
	//Start of user code for attributes
	// Other attributes
	//End of user code

	/**
	 * The logger
	 */
	private static final Logger logger = LoggerFactory.getLogger(OrderBean.class);

	
	@javax.persistence.OneToOne(optional = true, cascade = javax.persistence.CascadeType.ALL)
	private CartBean cart;
	@javax.persistence.Column(name = "CREATION_DATE")
	@javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date creationDate;
	
	@javax.persistence.ManyToOne(cascade = javax.persistence.CascadeType.ALL)
	private CustomerBean customer;
	
	@javax.persistence.Column(name = "DATECOLUMN")
	private String date;
	
	@javax.persistence.ManyToOne(cascade = javax.persistence.CascadeType.ALL)
	private AddressBean deliveryAddress;
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "seq", initialValue = 1, allocationSize = 10)
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.SEQUENCE, generator = "seq")
	@javax.persistence.Column(name = "ID")
	private long id;
	
	@javax.persistence.ManyToMany(cascade = javax.persistence.CascadeType.ALL, fetch = javax.persistence.FetchType.EAGER)
	@javax.persistence.JoinTable(name = "ORDER_ITEMS")
	private java.util.Set<ItemBean> items;
	
	@javax.persistence.ManyToOne(cascade = javax.persistence.CascadeType.ALL)
	private AddressBean paymentAddress;
	
	private String reference;
	
	private String status;
	@javax.persistence.Column(name = "UPDATE_DATE")
	@javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date updateDate;
	@javax.persistence.Version
	@javax.persistence.Column(name = "VERSIONCOLUMN")
	private int version;

	@javax.persistence.Transient
	private Order wrapper;
    	
	/**
	 * The current UUID of this object.<br>
	 * It's generated by the JPA provider, so you do not have to do it yourself.<br>
	 * <br>
	 * 
	 * @see <a
	 *      href="http://openjpa.apache.org/builds/2.1.1/apache-openjpa-2.1.1/docs/jpa_overview_meta_field.html#jpa_overview_meta_gen">jpa
	 *      documentation</a>
	 * @see <a href="http://fr.wikipedia.org/wiki/UUID">wikipedia</a>
	 */
	@javax.persistence.Column(name = "UUID", columnDefinition = "CHAR(36)")
	protected String uuid;
	/*
	 * <!-- Start of user code comment for Order wrapper getter
	 * End of user code -->
	 */
	@javax.persistence.Transient
	@Override
	public Order getWrapper() {
		if (wrapper == null) {
			wrapper = new Order(this);
		}
		return wrapper;
	}
	
	@javax.persistence.Transient
	@Override
	public boolean isWrapped() { 
		return wrapper != null;
	}
	
	/*
	 * <!-- Start of user code comment for Order wrapper setter
	 * End of user code -->
	 */
	@javax.persistence.Transient
	public void setWrapper(Order wrapper) {
		if (this.wrapper != null && this.wrapper != wrapper) {
			throw new RuntimeException("A bean can only have one wrapper, use #getWrapper instead");
		}
		this.wrapper = wrapper;
	}

	/**
	 * Configure date and identifiant when persisting the object the first time
	 */
	@javax.persistence.PrePersist
	void initDates() {
		updateDate = new java.util.Date();
		creationDate = new java.util.Date();
		if (uuid == null) {
			uuid = java.util.UUID.randomUUID().toString();
		}
	}
	
	/**
	 * Configure the update date when updating the object
	 */
	@javax.persistence.PreUpdate
	void initUpdateDate() {
		updateDate = new java.util.Date();
	}
	

	/*
	 * <!-- Start of user code comment for cart getter
	 * End of user code -->
	 */
	public CartBean getCart(){
		return this.cart;
	}
	
	/*
	 * <!-- Start of user code comment for cart setter
	 * End of user code -->
	 */
	public void setCart(CartBean arg0){
		this.cart = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for cart unsetter
	 * End of user code -->
	 */
	public void unsetCart(){
			if (this.cart == null) {
				return;
			}
			CartBean oldcart = this.cart;
			this.cart = null;
			oldcart.unsetOrder();
	} 
	/*
	 * <!-- Start of user code comment for creationDate getter
	 * End of user code -->
	 */
	public java.util.Date getCreationDate(){
		return this.creationDate;
	}
	
	/*
	 * <!-- Start of user code comment for creationDate setter
	 * End of user code -->
	 */
	public void setCreationDate(java.util.Date arg0){
		this.creationDate = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for creationDate unsetter
	 * End of user code -->
	 */
	public void unsetCreationDate(java.util.Date arg0){
		this.creationDate = null;
	}
	/*
	 * <!-- Start of user code comment for customer getter
	 * End of user code -->
	 */
	public CustomerBean getCustomer(){
		return this.customer;
	}
	
	/*
	 * <!-- Start of user code comment for customer setter
	 * End of user code -->
	 */
	public void setCustomer(CustomerBean arg0){
		this.customer = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for customer unsetter
	 * End of user code -->
	 */
	public void unsetCustomer(){
			this.customer = null;
			
	} 
	/*
	 * <!-- Start of user code comment for date getter
	 * End of user code -->
	 */
	public String getDate(){
		return this.date;
	}
	
	/*
	 * <!-- Start of user code comment for date setter
	 * End of user code -->
	 */
	public void setDate(String arg0){
		this.date = arg0;
	}
	/*
	 * <!-- Start of user code comment for deliveryAddress getter
	 * End of user code -->
	 */
	public AddressBean getDeliveryAddress(){
		return this.deliveryAddress;
	}
	
	/*
	 * <!-- Start of user code comment for deliveryAddress setter
	 * End of user code -->
	 */
	public void setDeliveryAddress(AddressBean arg0){
		this.deliveryAddress = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for deliveryAddress unsetter
	 * End of user code -->
	 */
	public void unsetDeliveryAddress(){
			this.deliveryAddress = null;
			
	} 
	/*
	 * <!-- Start of user code comment for id getter
	 * End of user code -->
	 */
	public long getId(){
		return this.id;
	}
	
	/*
	 * <!-- Start of user code comment for id setter
	 * End of user code -->
	 */
	public void setId(long arg0){
		this.id = arg0;
	}
	/*
	 * <!-- Start of user code comment for items getter
	 * End of user code -->
	 */
	public java.util.List<ItemBean> getItems(){
			if(this.items==null) {
				this.items= new java.util.HashSet<ItemBean>();
			}
			return new java.util.ArrayList<ItemBean>(this.items);
	}
	
	/*
	 * <!-- Start of user code comment for items adder
	 * End of user code -->
	 */
	public void addItems(ItemBean newItems){
		if(this.items==null) {
				this.items= new java.util.HashSet<ItemBean>();
			}
				
			this.items.add (newItems);
	} 
	/*
	 * <!-- Start of user code comment for paymentAddress getter
	 * End of user code -->
	 */
	public AddressBean getPaymentAddress(){
		return this.paymentAddress;
	}
	
	/*
	 * <!-- Start of user code comment for paymentAddress setter
	 * End of user code -->
	 */
	public void setPaymentAddress(AddressBean arg0){
		this.paymentAddress = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for paymentAddress unsetter
	 * End of user code -->
	 */
	public void unsetPaymentAddress(){
			this.paymentAddress = null;
			
	} 
	/*
	 * <!-- Start of user code comment for reference getter
	 * End of user code -->
	 */
	public String getReference(){
		return this.reference;
	}
	
	/*
	 * <!-- Start of user code comment for reference setter
	 * End of user code -->
	 */
	public void setReference(String arg0){
		this.reference = arg0;
	}
	/*
	 * <!-- Start of user code comment for status getter
	 * End of user code -->
	 */
	public String getStatus(){
		return this.status;
	}
	
	/*
	 * <!-- Start of user code comment for status setter
	 * End of user code -->
	 */
	public void setStatus(String arg0){
		this.status = arg0;
	}
	/*
	 * <!-- Start of user code comment for updateDate getter
	 * End of user code -->
	 */
	public java.util.Date getUpdateDate(){
		return this.updateDate;
	}
	
	/*
	 * <!-- Start of user code comment for updateDate setter
	 * End of user code -->
	 */
	public void setUpdateDate(java.util.Date arg0){
		this.updateDate = arg0;
	}
	
	/*
	 * <!-- Start of user code comment for updateDate unsetter
	 * End of user code -->
	 */
	public void unsetUpdateDate(java.util.Date arg0){
		this.updateDate = null;
	}
	/*
	 * <!-- Start of user code comment for version getter
	 * End of user code -->
	 */
	public int getVersion(){
		return this.version;
	}
	
	/*
	 * <!-- Start of user code comment for version setter
	 * End of user code -->
	 */
	public void setVersion(int arg0){
		this.version = arg0;
	}
    

	public Element toXML(){
		Element xmlElement = new Element("Order");
		if (uuid != null)
			xmlElement.setAttribute(new Attribute("uuid", uuid));
		if (getReference() != null)
			xmlElement.setAttribute(new Attribute("reference", getReference()));
		if (getStatus() != null)
			xmlElement.setAttribute(new Attribute("status", getStatus()));
		if (getDate() != null)
			xmlElement.setAttribute(new Attribute("date", getDate()));
		xmlElement.setAttribute(new Attribute("id", String.valueOf(getId())));
		if (getCreationDate() != null)
			xmlElement.setAttribute(new Attribute("creationDate", getCreationDate().toString()));
		if (getUpdateDate() != null)
			xmlElement.setAttribute(new Attribute("updateDate", getUpdateDate().toString()));
		xmlElement.setAttribute(new Attribute("version", String.valueOf(getVersion())));
		
		if (getDeliveryAddress() != null)
			xmlElement.setAttribute("deliveryAddress", String.valueOf(getDeliveryAddress().getId()));
		if (getCart() != null)
			xmlElement.setAttribute("cart", String.valueOf(getCart().getId()));
		if (!getItems().isEmpty()) {
			Element items = new Element("items");
			for (ItemBean tmp : getItems())
				items.addContent(new Element("Item", String.valueOf(tmp.getId())));
			xmlElement.addContent(items);
		}
		if (getCustomer() != null)
			xmlElement.setAttribute("customer", String.valueOf(getCustomer().getId()));
		if (getPaymentAddress() != null)
			xmlElement.setAttribute("paymentAddress", String.valueOf(getPaymentAddress().getId()));
		
		return xmlElement;
	}

	//Start of user code for methods
	// Other methods
	//End of user code

}
