// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package easyinheritance.domain;

import easyinheritance.domain.B;
import easyinheritance.domain.D;

privileged aspect D_Roo_JavaBean {
    
    public B D.getB() {
        return this.b;
    }
    
    public void D.setB(B b) {
        this.b = b;
    }
    
}
