// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package easyinheritance.domain;

import easyinheritance.domain.MyA;
import javax.persistence.Entity;

privileged aspect MyA_Roo_Jpa_Entity {
    
    declare @type: MyA: @Entity;
    
}
