// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package easyinheritance.domain;

import easyinheritance.domain.MyA;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MyA_Roo_Configurable {
    
    declare @type: MyA: @Configurable;
    
}
