// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package easyinheritance.domain;

import easyinheritance.domain.MyC;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MyC_Roo_Configurable {
    
    declare @type: MyC: @Configurable;
    
}
